//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika2
{
    using System;
    using System.Collections.Generic;
    
    public partial class marks
    {
        public int markID { get; set; }
        public int mark { get; set; }
        public string FK_user { get; set; }
        public int FK_lectures { get; set; }
    
        public virtual lectures lectures { get; set; }
    }
}
